icons_format = "{icon}"

[theme]
theme = "plain"
# theme = "ctp-frappe"

[icons]
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "
# volume = "V"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available/$total "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used/$mem_total "
# format = " $icon $mem_total_used_percents.eng(w:2) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
# [[block.format]]

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S') "
